name = "theorium-v2"
compatibility_date = "2026-03-28"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "theorium.eu", custom_domain = true },
  { pattern = "www.theorium.eu", custom_domain = true },
]

[assets]
directory = "./dist"
