export type {
  NavItem,
  NavCTA,
  NavConfig,
  SocialLinks,
  FooterColumn,
  FooterConfig,
  AddressConfig,
  ContactConfig,
  SEOConfig,
  AnalyticsConfig,
  CMSConfig,
  ThemeConfig,
  SiteConfig,
} from './types.js';
