-- Seed data for development (all is_live = 1, expires far in the future)
INSERT INTO jobs (slug, company_name, company_website, contact_email, title, description, country, industry, salary_range, visa_support, relocation_pkg, working_language, apply_url, is_live, created_at, activated_at, expires_at) VALUES
('senior-frontend-engineer-berlin-germany', 'Delivery Hero', 'https://deliveryhero.com', 'jobs@deliveryhero.com', 'Senior Frontend Engineer', 'We are looking for a Senior Frontend Engineer to join our team in Berlin. You will work on our consumer-facing web applications using React, TypeScript, and Next.js. We offer a competitive salary, relocation support, and a diverse international team.', 'Germany', 'Technology', '€70,000 – €95,000', 'yes', 'yes', 'English', 'https://careers.deliveryhero.com/frontend', 1, 1742600000, 1742600000, 1774136000),

('digital-marketing-manager-lisbon-portugal', 'Farfetch', 'https://farfetch.com', 'talent@farfetch.com', 'Digital Marketing Manager', 'Join Farfetch in Lisbon to lead our digital marketing efforts across paid social, SEM, and programmatic channels. You will manage a team of 4 and report directly to the VP of Marketing. Lisbon is one of Europe''s most vibrant cities with excellent quality of life.', 'Portugal', 'Digital Marketing', '€45,000 – €60,000', 'yes', 'allowance_only', 'English', 'https://farfetch.com/careers/marketing', 1, 1742500000, 1742500000, 1774036000),

('renewable-energy-project-manager-amsterdam-netherlands', 'Vattenfall', 'https://vattenfall.com', 'careers@vattenfall.com', 'Renewable Energy Project Manager', 'Vattenfall is hiring a Project Manager to oversee wind farm installations across the Netherlands. You will coordinate with engineering teams, local authorities, and stakeholders. Experience in renewable energy or large-scale infrastructure projects required.', 'Netherlands', 'Renewable Energy', '€65,000 – €85,000', 'yes', 'yes', 'English', 'https://vattenfall.com/careers', 1, 1742400000, 1742400000, 1773936000),

('head-chef-dubai-uae', 'Jumeirah Group', 'https://jumeirah.com', 'recruitment@jumeirah.com', 'Head Chef — Mediterranean Cuisine', 'Lead the kitchen at our flagship Mediterranean restaurant in Dubai. We are looking for a chef with 10+ years of experience in fine dining. Tax-free salary, accommodation provided, and annual flights home included in the package.', 'United Arab Emirates', 'Hospitality & Tourism', '$8,000 – $12,000/month', 'yes', 'yes', 'English', 'mailto:recruitment@jumeirah.com', 1, 1742300000, 1742300000, 1773836000),

('fintech-backend-developer-zurich-switzerland', 'SIX Group', 'https://six-group.com', 'hr@six-group.com', 'Backend Developer — Fintech', 'Join SIX Group in Zurich to build the infrastructure powering the Swiss financial markets. You will work with Go, Kubernetes, and event-driven architectures. Swiss work permit sponsorship provided for qualified candidates.', 'Switzerland', 'Finance & Fintech', 'CHF 110,000 – CHF 140,000', 'yes', 'yes', 'English', 'https://six-group.com/careers', 1, 1742200000, 1742200000, 1773736000),

('nursing-staff-nurse-oslo-norway', 'Oslo University Hospital', 'https://oslo-universitetssykehus.no', 'jobs@ous-hf.no', 'Staff Nurse — Cardiology', 'Oslo University Hospital is recruiting international nurses for its cardiology department. Full-time permanent position. We provide Norwegian language training, relocation assistance, and help with professional registration. Prior hospital experience required.', 'Norway', 'Healthcare', 'NOK 500,000 – NOK 600,000', 'yes', 'yes', 'Local language', 'https://oslo-universitetssykehus.no/careers', 1, 1742100000, 1742100000, 1773636000),

('construction-site-manager-doha-qatar', 'QDVC', 'https://qdvc.com', 'recruitment@qdvc.com', 'Construction Site Manager', 'Manage large-scale infrastructure projects in Doha. We are building metro extensions and new stadiums. You will oversee a team of 50+ workers. Tax-free salary, accommodation, and annual leave flights provided.', 'Qatar', 'Construction', '$7,000 – $10,000/month', 'yes', 'yes', 'English', 'https://qdvc.com/careers', 1, 1742000000, 1742000000, 1773536000),

('english-teacher-tokyo-japan', 'ECC Foreign Language Institute', 'https://ecc.co.jp', 'recruit@ecc.co.jp', 'English Teacher — Tokyo', 'Teach English at our schools across Tokyo. No Japanese required. We provide visa sponsorship, initial accommodation, training, and a competitive salary. Ideal for native English speakers with a bachelor''s degree.', 'Japan', 'Education', '¥250,000 – ¥300,000/month', 'yes', 'yes', 'English', 'https://ecc.co.jp/teach-in-japan', 1, 1741900000, 1741900000, 1773436000),

('data-scientist-stockholm-sweden', 'Spotify', 'https://spotify.com', 'jobs@spotify.com', 'Data Scientist — Personalization', 'Join Spotify''s Personalization team in Stockholm. You will build ML models that power Discover Weekly and other recommendation features. We offer relocation support, competitive equity package, and flexible working arrangements.', 'Sweden', 'Technology', 'SEK 55,000 – SEK 70,000/month', 'yes', 'yes', 'English', 'https://lifeatspotify.com/jobs', 1, 1741800000, 1741800000, 1773336000),

('hotel-general-manager-maldives', 'Soneva', 'https://soneva.com', 'careers@soneva.com', 'General Manager — Luxury Resort', 'Lead operations at our luxury eco-resort in the Maldives. You will manage 200+ staff and deliver world-class guest experiences. Accommodation on-island, meals, and annual flights included. 5+ years luxury hotel GM experience required.', 'Maldives', 'Hospitality & Tourism', '$120,000 – $160,000', 'yes', 'yes', 'English', 'mailto:careers@soneva.com', 1, 1741700000, 1741700000, 1773236000),

('product-designer-copenhagen-denmark', 'Pleo', 'https://pleo.io', 'hiring@pleo.io', 'Senior Product Designer', 'Pleo is looking for a Senior Product Designer in Copenhagen. You will own the design for our expense management platform used by thousands of companies. We offer relocation assistance and a great benefits package in one of the world''s most liveable cities.', 'Denmark', 'Technology', 'DKK 50,000 – DKK 65,000/month', 'yes', 'allowance_only', 'English', 'https://pleo.io/careers', 1, 1741600000, 1741600000, 1773136000),

('solar-installation-technician-malaga-spain', 'Iberdrola', 'https://iberdrola.com', 'rrhh@iberdrola.com', 'Solar Installation Technician', 'Install and maintain solar panel systems across southern Spain. You will work outdoors in a growing renewable energy market. Spanish language skills preferred but training provided. Competitive salary and benefits.', 'Spain', 'Renewable Energy', '€28,000 – €35,000', 'partial', 'allowance_only', 'Local language', 'https://iberdrola.com/careers', 1, 1741500000, 1741500000, 1773036000),

('devops-engineer-tallinn-estonia', 'Wise', 'https://wise.com', 'engineering@wise.com', 'DevOps Engineer', 'Join Wise in Tallinn to help scale our global money transfer infrastructure. You will work with AWS, Terraform, and Kubernetes. Estonia offers a fantastic tech scene, e-Residency program, and high quality of life at a lower cost than Western Europe.', 'Estonia', 'Finance & Fintech', '€55,000 – €75,000', 'yes', 'yes', 'English', 'https://wise.com/careers', 1, 1741400000, 1741400000, 1772936000),

('physiotherapist-melbourne-australia', 'Healthscope', 'https://healthscope.com.au', 'careers@healthscope.com.au', 'Physiotherapist — Sports Rehab', 'Join our sports rehabilitation clinic in Melbourne. We sponsor skilled worker visas for qualified physiotherapists. You will work with elite athletes and weekend warriors alike. AHPRA registration support provided.', 'Australia', 'Healthcare', 'AUD 80,000 – AUD 100,000', 'yes', 'yes', 'English', 'https://healthscope.com.au/careers', 1, 1741300000, 1741300000, 1772836000),

('full-stack-developer-singapore', 'Grab', 'https://grab.com', 'tech-hiring@grab.com', 'Full Stack Developer', 'Build products that serve millions of users across Southeast Asia. Grab is hiring Full Stack Developers in Singapore. Work with React, Node.js, Go, and microservices at scale. Relocation package and EP visa sponsorship included.', 'Singapore', 'Technology', 'SGD 8,000 – SGD 12,000/month', 'yes', 'yes', 'English', 'https://grab.careers', 1, 1741200000, 1741200000, 1772736000);
