name = "nikolaspetrou"
compatibility_date = "2026-03-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "nikolaspetrou.com", custom_domain = true },
  { pattern = "www.nikolaspetrou.com", custom_domain = true },
]

[assets]
directory = "./dist"

[vars]
SONICJS_URL = "https://admin.nikolaspetrou.com"
PREVIEW_TOKEN = "np-preview-2026-secret"
